config/routes.rb
Rails.application.routes.draw do
  resources :intro_texts

  resources :mottos

  resources :announcements

  resources :books

  resources :slides
  
  get 'world_citizen/prev_slide'
  get 'world_citizen/prev_ann'
  get 'world_citizen/prev_motto'
  
  get 'world_citizen/next_slide'
  get 'world_citizen/next_ann'
  get 'world_citizen/next_motto'
  
  get 'active_language/active'

  get 'laaszen_task/start'
  get 'laaszen_task/restart'
  post 'laaszen_task/translate'
  
  get 'laaszen_task/edit'
  post 'laaszen_task/edit_translation'
  
  post 'active_language/active'
  
  get 'books/book_shelf'
  get 'books/book_whole'
  get 'books/book_collapse'

  root 'world_citizen#home'

  get '/' => 'world_citizen#home'
  get '/shelf' => 'books#book_shelf'
  get '/bookw' => 'books#book_whole'
  get '/bookp' => 'books#book_collapse'

end

app/models/announcement.rb

class Announcement < ActiveRecord::Base 
    # mass assignment protection
    attr_accessor :language, :name, :content
    # Associations macro-style method invocations
    # Validations
    # Callbacks
    # Accessors overloading
    def language=(value)
        self[:language] = value
    end
    def language
        self[:language]
    end
    def name=(value)
        self[:name] = value
    end
    def name
        self[:name]
    end
    def content=(value)
        self[:content] = value
    end
    def content
        self[:content]
    end
    # Other definitions
    def upload_announcement=(data)
        self[:content] = data.read
    end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all
    @view_path = get_view_path(params)
    DavidEgan.new.make_dav_layout_compatible(@view_path)
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
    @view_path = get_view_path(params)
    DavidEgan.new.make_dav_layout_compatible(@view_path)
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
    @view_path = get_view_path(params)
    DavidEgan.new.make_dav_layout_compatible(@view_path)
  end

  # GET /announcements/1/edit
  def edit
    @view_path = get_view_path(params)
    DavidEgan.new.make_dav_layout_compatible(@view_path)
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:language, :name, :upload_announcement)
    end
    
    def get_view_path(params)
        return nil if params.nil?
        DavidEgan.new.get_view_path(params)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.file_field :upload_announcement %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing Announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb

            
<!-- CONTENT -->

            <div id="content" class="page_wrapper page_background">
                <div id="blog_content" class="columns_431">
                    <div class="three_quarters bottom_padding">
                        <div id="post-273" class="post_box top">
                            

<!-- David Egan Layout Compatible -->

<p id="notice"><%= notice %></p>

<h1>Listing Announcements</h1>

<table>
  <thead>
    <tr>
      <th>Language</th>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.language %></td>
        <td><%= announcement.name %></td>
        <td><%= announcement.content %></td>
        <td><%= link_to 'Show', announcement %></td>
        <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
        <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Announcement', new_announcement_path %>

                        </div>
                    </div>
                    
<!-- QUATER SIDE BAR -->

                    <div class="quarter sidebar">
                    </div>
                </div>
            </div>

app/views/announcements/new.html.erb

            
<!-- CONTENT -->

            <div id="content" class="page_wrapper page_background">
                <div id="blog_content" class="columns_431">
                    <div class="three_quarters bottom_padding">
                        <div id="post-273" class="post_box top">
                            

<!-- David Egan Layout Compatible -->

<h1>New Announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

                        </div>
                    </div>
                    
<!-- QUATER SIDE BAR -->

                    <div class="quarter sidebar">
                    </div>
                </div>
            </div>

app/views/announcements/show.html.erb

            
<!-- CONTENT -->

            <div id="content" class="page_wrapper page_background">
                <div id="blog_content" class="columns_431">
                    <div class="three_quarters bottom_padding">
                        <div id="post-273" class="post_box top">
                            

<!-- David Egan Layout Compatible -->

<p id="notice"><%= notice %></p>

<p>
  <strong>Language:</strong>
  <%= @announcement.language %>
</p>

<p>
  <strong>Name:</strong>
  <%= @announcement.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @announcement.content %>
</p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>

                        </div>
                    </div>
                    
<!-- QUATER SIDE BAR -->

                    <div class="quarter sidebar">
                    </div>
                </div>
            </div>