config/routes.rb
Rails.application.routes.draw do
  resources :intro_texts

  resources :mottos

  resources :announcements

  resources :books

  resources :slides
  
  get 'world_citizen/prev_slide'
  get 'world_citizen/prev_ann'
  get 'world_citizen/prev_motto'
  
  get 'world_citizen/next_slide'
  get 'world_citizen/next_ann'
  get 'world_citizen/next_motto'
  
  get 'active_language/active'

  get 'laaszen_task/start'
  get 'laaszen_task/restart'
  post 'laaszen_task/translate'
  
  get 'laaszen_task/edit'
  post 'laaszen_task/edit_translation'
  
  post 'active_language/active'
  
  get 'books/book_shelf'
  get 'books/book_whole'
  get 'books/book_collapse'

  root 'world_citizen#home'

  get '/' => 'world_citizen#home'
  get '/shelf' => 'books#book_shelf'
  get '/bookw' => 'books#book_whole'
  get '/bookp' => 'books#book_collapse'

end

app/models/slide.rb

class Slide < ActiveRecord::Base 
    # mass assignment protection
    attr_accessor :language, :author, :theme, :topic, :content
    # Associations macro-style method invocations
    # Validations
    # Callbacks
    # Accessors overloading
    def language=(value)
        self[:language] = value
    end
    def language
        self[:language]
    end
    def author=(value)
        self[:author] = value
    end
    def author
        self[:author]
    end
    def theme=(value)
        self[:theme] = value
    end
    def theme
        self[:theme]
    end
    def topic=(value)
        self[:topic] = value
    end
    def topic
        self[:topic]
    end
    def content=(value)
        self[:content] = value
    end
    def content
        self[:content]
    end
    # Other definitions
    def upload_slide=(data)
        self[:content] = data.read
    end
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all
    @view_path = get_view_path(params)
    DavidEgan.new.make_dav_layout_compatible(@view_path)
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
    @view_path = get_view_path(params)
    DavidEgan.new.make_dav_layout_compatible(@view_path)
  end

  # GET /slides/new
  def new
    @slide = Slide.new
    @view_path = get_view_path(params)
    DavidEgan.new.make_dav_layout_compatible(@view_path)
  end

  # GET /slides/1/edit
  def edit
    @view_path = get_view_path(params)
    DavidEgan.new.make_dav_layout_compatible(@view_path)
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(slide_params)

    respond_to do |format|
      if @slide.save
        format.html { redirect_to @slide, notice: 'Slide was successfully created.' }
        format.json { render :show, status: :created, location: @slide }
      else
        format.html { render :new }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to @slide, notice: 'Slide was successfully updated.' }
        format.json { render :show, status: :ok, location: @slide }
      else
        format.html { render :edit }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to slides_url, notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:language, :author, :theme, :topic, :upload_slide)
    end
    
    def get_view_path(params)
        return nil if params.nil?
        DavidEgan.new.get_view_path(params)
    end
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/slides/_form.html.erb
<%= form_for(@slide) do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :theme %><br>
    <%= f.text_field :theme %>
  </div>
  <div class="field">
    <%= f.label :topic %><br>
    <%= f.text_field :topic %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.file_field :upload_slide %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slides/edit.html.erb

            
<!-- CONTENT -->

            <div id="content" class="page_wrapper page_background">
                <div id="blog_content" class="columns_431">
                    <div class="three_quarters bottom_padding">
                        <div id="post-273" class="post_box top">
                            

<!-- David Egan Layout Compatible -->

<h1>Editing Slide</h1>

<%= render 'form' %>

<%= link_to 'Show', @slide %> |
<%= link_to 'Back', slides_path %>

                        </div>
                    </div>
                    
<!-- QUATER SIDE BAR -->

                    <div class="quarter sidebar">
                    </div>
                </div>
            </div>

app/views/slides/index.html.erb

            
<!-- CONTENT -->

            <div id="content" class="page_wrapper page_background">
                <div id="blog_content" class="columns_431">
                    <div class="three_quarters bottom_padding">
                        <div id="post-273" class="post_box top">
                            

<!-- David Egan Layout Compatible -->

<p id="notice"><%= notice %></p>

<h1>Listing Slides</h1>

<table>
  <thead>
    <tr>
      <th>Language</th>
      <th>Author</th>
      <th>Theme</th>
      <th>Topic</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slides.each do |slide| %>
      <tr>
        <td><%= slide.language %></td>
        <td><%= slide.author %></td>
        <td><%= slide.theme %></td>
        <td><%= slide.topic %></td>
        <td><%= slide.content %></td>
        <td><%= link_to 'Show', slide %></td>
        <td><%= link_to 'Edit', edit_slide_path(slide) %></td>
        <td><%= link_to 'Destroy', slide, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slide', new_slide_path %>

                        </div>
                    </div>
                    
<!-- QUATER SIDE BAR -->

                    <div class="quarter sidebar">
                    </div>
                </div>
            </div>

app/views/slides/new.html.erb

            
<!-- CONTENT -->

            <div id="content" class="page_wrapper page_background">
                <div id="blog_content" class="columns_431">
                    <div class="three_quarters bottom_padding">
                        <div id="post-273" class="post_box top">
                            

<!-- David Egan Layout Compatible -->

<h1>New Slide</h1>

<%= render 'form' %>

<%= link_to 'Back', slides_path %>

                        </div>
                    </div>
                    
<!-- QUATER SIDE BAR -->

                    <div class="quarter sidebar">
                    </div>
                </div>
            </div>

app/views/slides/show.html.erb

            
<!-- CONTENT -->

            <div id="content" class="page_wrapper page_background">
                <div id="blog_content" class="columns_431">
                    <div class="three_quarters bottom_padding">
                        <div id="post-273" class="post_box top">
                            

<!-- David Egan Layout Compatible -->

<p id="notice"><%= notice %></p>

<p>
  <strong>Language:</strong>
  <%= @slide.language %>
</p>

<p>
  <strong>Author:</strong>
  <%= @slide.author %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @slide.theme %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @slide.topic %>
</p>

<p>
  <strong>Content:</strong>
  <%= @slide.content %>
</p>

<%= link_to 'Edit', edit_slide_path(@slide) %> |
<%= link_to 'Back', slides_path %>

                        </div>
                    </div>
                    
<!-- QUATER SIDE BAR -->

                    <div class="quarter sidebar">
                    </div>
                </div>
            </div>