config/routes.rb
Rails.application.routes.draw do
  resources :intro_texts

  resources :mottos

  resources :announcements

  resources :books

  resources :slides
  
  get 'world_citizen/prev_slide'
  get 'world_citizen/prev_ann'
  get 'world_citizen/prev_motto'
  
  get 'world_citizen/next_slide'
  get 'world_citizen/next_ann'
  get 'world_citizen/next_motto'
  
  get 'active_language/active'

  get 'laaszen_task/start'
  get 'laaszen_task/restart'
  post 'laaszen_task/translate'
  
  get 'laaszen_task/edit'
  post 'laaszen_task/edit_translation'
  
  post 'active_language/active'
  
  get 'books/book_shelf'
  get 'books/book_whole'
  get 'books/book_collapse'

  root 'world_citizen#home'

  get '/' => 'world_citizen#home'
  get '/shelf' => 'books#book_shelf'
  get '/bookw' => 'books#book_whole'
  get '/bookp' => 'books#book_collapse'

end

app/models/intro_text.rb

class IntroText < ActiveRecord::Base 
    # mass assignment protection
    attr_accessor :language, :content
    # Associations macro-style method invocations
    # Validations
    # Callbacks
    # Accessors overloading
    def language=(value)
        self[:language] = value
    end
    def language
        self[:language]
    end
    def content=(value)
        self[:content] = value
    end
    def content
        self[:content]
    end
    # Other definitions
    def upload_intro_text=(data)
        self[:content] = data.read
    end
end

app/controllers/intro_texts_controller.rb
class IntroTextsController < ApplicationController
  before_action :set_intro_text, only: [:show, :edit, :update, :destroy]

  # GET /intro_texts
  # GET /intro_texts.json
  def index
    @intro_texts = IntroText.all
    @view_path = get_view_path(params)
    DavidEgan.new.make_dav_layout_compatible(@view_path)
  end

  # GET /intro_texts/1
  # GET /intro_texts/1.json
  def show
    @view_path = get_view_path(params)
    DavidEgan.new.make_dav_layout_compatible(@view_path)
  end

  # GET /intro_texts/new
  def new
    @intro_text = IntroText.new
    @view_path = get_view_path(params)
    DavidEgan.new.make_dav_layout_compatible(@view_path)
  end

  # GET /intro_texts/1/edit
  def edit
    @view_path = get_view_path(params)
    DavidEgan.new.make_dav_layout_compatible(@view_path)
  end

  # POST /intro_texts
  # POST /intro_texts.json
  def create
    @intro_text = IntroText.new(intro_text_params)

    respond_to do |format|
      if @intro_text.save
        format.html { redirect_to @intro_text, notice: 'Intro text was successfully created.' }
        format.json { render :show, status: :created, location: @intro_text }
      else
        format.html { render :new }
        format.json { render json: @intro_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /intro_texts/1
  # PATCH/PUT /intro_texts/1.json
  def update
    respond_to do |format|
      if @intro_text.update(intro_text_params)
        format.html { redirect_to @intro_text, notice: 'Intro text was successfully updated.' }
        format.json { render :show, status: :ok, location: @intro_text }
      else
        format.html { render :edit }
        format.json { render json: @intro_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /intro_texts/1
  # DELETE /intro_texts/1.json
  def destroy
    @intro_text.destroy
    respond_to do |format|
      format.html { redirect_to intro_texts_url, notice: 'Intro text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intro_text
      @intro_text = IntroText.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def intro_text_params
      params.require(:intro_text).permit(:language, :upload_intro_text)
    end
    
    def get_view_path(params)
        return nil if params.nil?
        DavidEgan.new.get_view_path(params)
    end
end

app/helpers/intro_texts_helper.rb
module IntroTextsHelper
end

app/views/intro_texts/_form.html.erb
<%= form_for(@intro_text) do |f| %>
  <% if @intro_text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@intro_text.errors.count, "error") %> prohibited this intro_text from being saved:</h2>

      <ul>
      <% @intro_text.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.file_field :upload_intro_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/intro_texts/edit.html.erb

            
<!-- CONTENT -->

            <div id="content" class="page_wrapper page_background">
                <div id="blog_content" class="columns_431">
                    <div class="three_quarters bottom_padding">
                        <div id="post-273" class="post_box top">
                            

<!-- David Egan Layout Compatible -->

<h1>Editing Intro Text</h1>

<%= render 'form' %>

<%= link_to 'Show', @intro_text %> |
<%= link_to 'Back', intro_texts_path %>

                        </div>
                    </div>
                    
<!-- QUATER SIDE BAR -->

                    <div class="quarter sidebar">
                    </div>
                </div>
            </div>

app/views/intro_texts/index.html.erb

            
<!-- CONTENT -->

            <div id="content" class="page_wrapper page_background">
                <div id="blog_content" class="columns_431">
                    <div class="three_quarters bottom_padding">
                        <div id="post-273" class="post_box top">
                            

<!-- David Egan Layout Compatible -->

<p id="notice"><%= notice %></p>

<h1>Listing Intro Texts</h1>

<table>
  <thead>
    <tr>
      <th>Language</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @intro_texts.each do |intro_text| %>
      <tr>
        <td><%= intro_text.language %></td>
        <td><%= intro_text.content %></td>
        <td><%= link_to 'Show', intro_text %></td>
        <td><%= link_to 'Edit', edit_intro_text_path(intro_text) %></td>
        <td><%= link_to 'Destroy', intro_text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intro text', new_intro_text_path %>

                        </div>
                    </div>
                    
<!-- QUATER SIDE BAR -->

                    <div class="quarter sidebar">
                    </div>
                </div>
            </div>

app/views/intro_texts/new.html.erb

            
<!-- CONTENT -->

            <div id="content" class="page_wrapper page_background">
                <div id="blog_content" class="columns_431">
                    <div class="three_quarters bottom_padding">
                        <div id="post-273" class="post_box top">
                            

<!-- David Egan Layout Compatible -->

<h1>New Intro Text</h1>

<%= render 'form' %>

<%= link_to 'Back', intro_texts_path %>

                        </div>
                    </div>
                    
<!-- QUATER SIDE BAR -->

                    <div class="quarter sidebar">
                    </div>
                </div>
            </div>

app/views/intro_texts/show.html.erb

            
<!-- CONTENT -->

            <div id="content" class="page_wrapper page_background">
                <div id="blog_content" class="columns_431">
                    <div class="three_quarters bottom_padding">
                        <div id="post-273" class="post_box top">
                            

<!-- David Egan Layout Compatible -->

<p id="notice"><%= notice %></p>

<p>
  <strong>Language:</strong>
  <%= @intro_text.language %>
</p>

<p>
  <strong>Content:</strong>
  <%= @intro_text.content %>
</p>

<%= link_to 'Edit', edit_intro_text_path(@intro_text) %> |
<%= link_to 'Back', intro_texts_path %>

                        </div>
                    </div>
                    
<!-- QUATER SIDE BAR -->

                    <div class="quarter sidebar">
                    </div>
                </div>
            </div>