config/routes.rb
Rails.application.routes.draw do
  resources :intro_texts

  resources :mottos

  resources :announcements

  resources :books

  resources :slides
  
  get 'world_citizen/prev_slide'
  get 'world_citizen/prev_ann'
  get 'world_citizen/prev_motto'
  
  get 'world_citizen/next_slide'
  get 'world_citizen/next_ann'
  get 'world_citizen/next_motto'
  
  get 'active_language/active'

  get 'laaszen_task/start'
  get 'laaszen_task/restart'
  post 'laaszen_task/translate'
  
  get 'laaszen_task/edit'
  post 'laaszen_task/edit_translation'
  
  post 'active_language/active'
  
  get 'books/book_shelf'
  get 'books/book_whole'
  get 'books/book_collapse'

  root 'world_citizen#home'

  get '/' => 'world_citizen#home'
  get '/shelf' => 'books#book_shelf'
  get '/bookw' => 'books#book_whole'
  get '/bookp' => 'books#book_collapse'

end

app/models/motto.rb

class Motto < ActiveRecord::Base 
    # mass assignment protection
    attr_accessor :language, :name, :content
    # Associations macro-style method invocations
    # Validations
    # Callbacks
    # Accessors overloading
    def language=(value)
        self[:language] = value
    end
    def language
        self[:language]
    end
    def name=(value)
        self[:name] = value
    end
    def name
        self[:name]
    end
    def content=(value)
        self[:content] = value
    end
    def content
        self[:content]
    end
    # Other definitions
    def upload_motto=(data)
        self[:content] = data.read
    end
end

app/controllers/mottos_controller.rb
class MottosController < ApplicationController
  before_action :set_motto, only: [:show, :edit, :update, :destroy]

  # GET /mottos
  # GET /mottos.json
  def index
    @mottos = Motto.all
    @view_path = get_view_path(params)
    DavidEgan.new.make_dav_layout_compatible(@view_path)
  end

  # GET /mottos/1
  # GET /mottos/1.json
  def show
    @view_path = get_view_path(params)
    DavidEgan.new.make_dav_layout_compatible(@view_path)
  end

  # GET /mottos/new
  def new
    @motto = Motto.new
    @view_path = get_view_path(params)
    DavidEgan.new.make_dav_layout_compatible(@view_path)
  end

  # GET /mottos/1/edit
  def edit
    @view_path = get_view_path(params)
    DavidEgan.new.make_dav_layout_compatible(@view_path)
  end

  # POST /mottos
  # POST /mottos.json
  def create
    @motto = Motto.new(motto_params)

    respond_to do |format|
      if @motto.save
        format.html { redirect_to @motto, notice: 'Motto was successfully created.' }
        format.json { render :show, status: :created, location: @motto }
      else
        format.html { render :new }
        format.json { render json: @motto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mottos/1
  # PATCH/PUT /mottos/1.json
  def update
    respond_to do |format|
      if @motto.update(motto_params)
        format.html { redirect_to @motto, notice: 'Motto was successfully updated.' }
        format.json { render :show, status: :ok, location: @motto }
      else
        format.html { render :edit }
        format.json { render json: @motto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mottos/1
  # DELETE /mottos/1.json
  def destroy
    @motto.destroy
    respond_to do |format|
      format.html { redirect_to mottos_url, notice: 'Motto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motto
      @motto = Motto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def motto_params
      params.require(:motto).permit(:language, :name, :upload_motto)
    end
    
    def get_view_path(params)
        return nil if params.nil?
        DavidEgan.new.get_view_path(params)
    end
end

app/helpers/mottos_helper.rb
module MottosHelper
end

app/views/mottos/_form.html.erb
<%= form_for(@motto) do |f| %>
  <% if @motto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@motto.errors.count, "error") %> prohibited this motto from being saved:</h2>

      <ul>
      <% @motto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.file_field :upload_motto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mottos/edit.html.erb

            
<!-- CONTENT -->

            <div id="content" class="page_wrapper page_background">
                <div id="blog_content" class="columns_431">
                    <div class="three_quarters bottom_padding">
                        <div id="post-273" class="post_box top">
                            

<!-- David Egan Layout Compatible -->

<h1>Editing Motto</h1>

<%= render 'form' %>

<%= link_to 'Show', @motto %> |
<%= link_to 'Back', mottos_path %>

                        </div>
                    </div>
                    
<!-- QUATER SIDE BAR -->

                    <div class="quarter sidebar">
                    </div>
                </div>
            </div>

app/views/mottos/index.html.erb

            
<!-- CONTENT -->

            <div id="content" class="page_wrapper page_background">
                <div id="blog_content" class="columns_431">
                    <div class="three_quarters bottom_padding">
                        <div id="post-273" class="post_box top">
                            

<!-- David Egan Layout Compatible -->

<p id="notice"><%= notice %></p>

<h1>Listing Mottos</h1>

<table>
  <thead>
    <tr>
      <th>Language</th>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mottos.each do |motto| %>
      <tr>
        <td><%= motto.language %></td>
        <td><%= motto.name %></td>
        <td><%= motto.content %></td>
        <td><%= link_to 'Show', motto %></td>
        <td><%= link_to 'Edit', edit_motto_path(motto) %></td>
        <td><%= link_to 'Destroy', motto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Motto', new_motto_path %>

                        </div>
                    </div>
                    
<!-- QUATER SIDE BAR -->

                    <div class="quarter sidebar">
                    </div>
                </div>
            </div>

app/views/mottos/new.html.erb

            
<!-- CONTENT -->

            <div id="content" class="page_wrapper page_background">
                <div id="blog_content" class="columns_431">
                    <div class="three_quarters bottom_padding">
                        <div id="post-273" class="post_box top">
                            

<!-- David Egan Layout Compatible -->

<h1>New Motto</h1>

<%= render 'form' %>

<%= link_to 'Back', mottos_path %>

                        </div>
                    </div>
                    
<!-- QUATER SIDE BAR -->

                    <div class="quarter sidebar">
                    </div>
                </div>
            </div>

app/views/mottos/show.html.erb

            
<!-- CONTENT -->

            <div id="content" class="page_wrapper page_background">
                <div id="blog_content" class="columns_431">
                    <div class="three_quarters bottom_padding">
                        <div id="post-273" class="post_box top">
                            

<!-- David Egan Layout Compatible -->

<p id="notice"><%= notice %></p>

<p>
  <strong>Language:</strong>
  <%= @motto.language %>
</p>

<p>
  <strong>Name:</strong>
  <%= @motto.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @motto.content %>
</p>

<%= link_to 'Edit', edit_motto_path(@motto) %> |
<%= link_to 'Back', mottos_path %>

                        </div>
                    </div>
                    
<!-- QUATER SIDE BAR -->

                    <div class="quarter sidebar">
                    </div>
                </div>
            </div>